{{- range $chartName, $chart := omit .Values "general" }}
{{- with $chart -}}
{{- if .enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  chart:
    spec:
      chart: {{ .chart.name }}
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: {{ .chart.name | default .name }}
      version: {{ .chart.version }}
  {{- with .values }}
  values: |
  {{- toYaml . | nindent 4 }}
  {{- end }}
  interval: {{ .chart.interval | default "5m" }}
{{- end }}
{{- end }}
{{- end }}

