{{- range $chartName, $chart := omit .Values "general" }}
{{- with $chart -}}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
spec: {}
{{- end }}
{{- end }}
{{- end }}

