{{- range $chartName, $chart := omit .Values "general" }}
{{- with $chart -}}
{{- if and (.enabled) (not .skipNamespaceCreation) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
spec: {}
{{- end }}
{{- end }}
{{- end }}

