# Default values for hauke-cloud-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# Cert Manager
certManager:
  name: cert-manager
  namespace: cert-manager
  enabled: true
  chart:
    name: cert-manager
    version: 1.18.2
  repository:
    name: jetstack
    url: https://charts.jetstack.io
  values:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
    cainjector:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    startupapicheck:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    crds:
      enabled: true

# External DNS
externalDNS:
  name: external-dns
  namespace: external-dns
  enabled: true
  chart:
    name: external-dns
    version: 1.18.0
  repository:
    name: kubernetes-sigs
    url: https://kubernetes-sigs.github.io/external-dns/
  values:
    triggerLoopOnEvent: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi

# External Secrets
externalSecrets:
  name: external-secrets
  namespace: external-secrets
  enabled: false
  chart:
    name: external-secrets
    version: 0.16.2
  repository:
    url: https://charts.external-secrets.io
  values:
    resources:
      requests:
        cpu: 250m
        memory: 384Mi
      limits:
        memory: 512Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 128Mi
    certController:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi

# sealed-secrets
sealedSecrets:
  name: sealed-secrets
  namespace: sealed-secrets
  enabled: true
  chart:
    name: sealed-secrets
    version: 2.17.4
  repository:
    url: https://bitnami-labs.github.io/sealed-secrets
  values:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi

# Nginx Ingress Controller
ingress:
  name: ingress
  namespace: ingress
  enabled: true
  chart:
    name: ingress-nginx
    version: 4.13.1
  repository:
    url: https://kubernetes.github.io/ingress-nginx
  values:
    controller:
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      service:
        annotations:
          load-balancer.hetzner.cloud/location: nbg1

reflector:
  name: reflector
  namespace: kube-system
  enabled: true
  chart:
    name: reflector
    version: 9.2.0-develop.18
  repository:
    url: oci://ghcr.io/emberstack/helm-charts/reflector
