# Default values for hauke-cloud-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# Cert Manager
certManager:
  name: cert-manager
  namespace: cert-manager
  enabled: true
  chart:
    name: cert-manager
    version: 1.19.0
  repository:
    name: jetstack
    url: https://charts.jetstack.io
  values:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
    cainjector:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    startupapicheck:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi
    crds:
      enabled: true

# External DNS
externalDNS:
  name: external-dns
  namespace: external-dns
  enabled: true
  chart:
    name: external-dns
    version: 1.18.0
  repository:
    name: kubernetes-sigs
    url: https://kubernetes-sigs.github.io/external-dns/
  values:
    triggerLoopOnEvent: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi

# External Secrets
externalSecrets:
  name: external-secrets
  namespace: external-secrets
  enabled: false
  chart:
    name: external-secrets
    version: 0.16.2
  repository:
    url: https://charts.external-secrets.io
  values:
    resources:
      requests:
        cpu: 250m
        memory: 384Mi
      limits:
        memory: 512Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 128Mi
    certController:
      resources:
        requests:
          cpu: 50m
          memory: 96Mi
        limits:
          memory: 96Mi

# sealed-secrets
sealedSecrets:
  name: sealed-secrets
  namespace: sealed-secrets
  enabled: true
  chart:
    name: sealed-secrets
    version: 2.17.4
  repository:
    url: https://bitnami-labs.github.io/sealed-secrets
  values:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi

# Nginx Ingress Controller
ingress:
  name: ingress
  namespace: ingress
  enabled: true
  chart:
    name: ingress-nginx
    version: 4.13.3
  repository:
    url: https://kubernetes.github.io/ingress-nginx
  values:
    controller:
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          memory: 200Mi
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      service:
        annotations:
          load-balancer.hetzner.cloud/location: nbg1

# Reflector
reflector:
  name: reflector
  namespace: kube-system
  enabled: false
  chart:
    name: reflector
    version: 9.2.0-develop.18
  repository:
    url: oci://ghcr.io/emberstack/helm-charts
    type: oci

# OpenCost
opencost:
  name: opencost
  namespace: opencost
  enabled: false
  chart:
    name: opencost
    version: 2.3.1
  repository:
    url: https://opencost.github.io/opencost-helm-chart

# Hetzner CSI
hetznerCSI:
  name: hetzner-csi
  namespace: kube-system
  enabled: false
  chart:
    name: hcloud-csi
    version: 2.18.0
  repository:
    url: https://charts.hetzner.cloud
  values:
    controller:
      resources:
        csiAttacher:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        csiResizer:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        csiProvisioner:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        livenessProbe:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        hcloudCSIDriver:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
    node:
      resources:
        csiNodeDriverRegistrar:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        livenessProbe:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi
        hcloudCSIDriver:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            memory: 50Mi

# Kubernetes metrics server
metricsServer:
  name: metrics-server
  namespace: kube-system
  skipNamespaceCreation: true
  enabled: true
  chart:
    name: metrics-server
    version: 3.13.0
  repository:
    url: https://kubernetes-sigs.github.io/metrics-server
  values:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 200Mi

# Hetzner Cloud Controller Manager
hetznerCloudControllerManager:
  name: hetzner-cloud-controller-manager
  namespace: kube-system
  skipNamespaceCreation: true
  enabled: true
  chart:
    name: hcloud-cloud-controller-manager
    version: 1.27.0
  repository:
    url: https://charts.hetzner.cloud
  value:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        memory: 50Mi

# Cilium
cilium:
  name: cilium
  namespace: kube-system
  skipNamespaceCreation: true
  enabled: true
  chart:
    name: cilium
    version: 1.18.2
  repository:
    url: https://helm.cilium.io
  values:
    hostFirewall:
      enabled: true
    extraArgs:
      - --direct-routing-device=eth0
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1Gi
    initResources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi
    cni:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 100Mi
    certgen:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 100Mi
    envoy:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 100Mi
    operator:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 100Mi
    nodeinit:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 100Mi

# Velero
velero:
  name: velero
  namespace: velero
  enabled: false
  chart:
    name: velero
    version: 11.0.0
  repository:
    url: https://vmware-tanzu.github.io/helm-charts
  values:
    resources:
      requests:
        cpu: 500m
        memory: 128Mi
      limits:
        memory: 512Mi
